/* App */
export const APP_LOADING = 'APP_LOADING';
export const REQUEST_JOBS_LOADING = 'REQUEST_JOBS_LOADING';
export const REQUEST_JOBVIEWS_LOADING = 'REQUEST_JOBVIEWS_LOADING';

/* Data */
export const REQUEST_INIT_DATA = 'REQUEST_INIT_DATA';
export const REQUEST_JOBS_DATA = 'REQUEST_JOBS_DATA';
export const REQUEST_JOBVIEWS_DATA = 'REQUEST_JOBVIEWS_DATA';
export const SET_JOBS_DATA = 'SET_JOBS_DATA';
export const SET_JOBVIEWS_DATA = 'SET_JOBVIEWS_DATA';

export const ERROR_DATA = 'ERROR_DATA';


